"""Change telegram_id to BIGINT

Revision ID: 1b7a462a6631
Revises: fd867aeed7b7
Create Date: 2025-03-01 08:04:06.650745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7a462a6631'
down_revision: Union[str, None] = 'fd867aeed7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('restaurant_message', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('delivery_message', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_message')
    op.drop_column('orders', 'restaurant_message')
    # ### end Alembic commands ###
