"""Initial migration

Revision ID: 215c5ca4fc41
Revises: fe6881f6444d
Create Date: 2025-02-28 13:22:07.357771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '215c5ca4fc41'
down_revision: Union[str, None] = 'fe6881f6444d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('restaurant_chat_id', sa.BigInteger(), nullable=True))
    op.drop_column('restaurants', 'retaurant_chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('retaurant_chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('restaurants', 'restaurant_chat_id')
    # ### end Alembic commands ###
