"""Change telegram_id to BIGINT

Revision ID: 69cf08659560
Revises: e1764f6e81bf
Create Date: 2025-03-03 06:37:02.524229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69cf08659560'
down_revision: Union[str, None] = 'e1764f6e81bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_messages', sa.Column('type', sa.String(length=50), nullable=False))
    op.add_column('delivery_messages', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_messages', 'created_at')
    op.drop_column('delivery_messages', 'type')
    # ### end Alembic commands ###
