"""Change telegram_id to BIGINT

Revision ID: c3cb846ced44
Revises: 42fdaaf9e701
Create Date: 2025-02-28 22:11:02.176084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cb846ced44'
down_revision: Union[str, None] = '42fdaaf9e701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_food', 'cart', ['user_id', 'food_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_food', 'cart', type_='unique')
    # ### end Alembic commands ###
