"""Change telegram_id to BIGINT

Revision ID: d03dd64c4a17
Revises: 1b7a462a6631
Create Date: 2025-03-01 09:38:26.648768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03dd64c4a17'
down_revision: Union[str, None] = '1b7a462a6631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cancellation_reason', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'cancellation_reason')
    # ### end Alembic commands ###
