"""Change telegram_id to BIGINT

Revision ID: d7f02ba4cd1c
Revises: c3cb846ced44
Create Date: 2025-03-01 05:44:59.705942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f02ba4cd1c'
down_revision: Union[str, None] = 'c3cb846ced44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('delivery_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'delivery_cost')
    # ### end Alembic commands ###
