"""Initial migration

Revision ID: f61180061f15
Revises: ba0f264f86a9
Create Date: 2025-02-28 13:10:57.426819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61180061f15'
down_revision: Union[str, None] = 'ba0f264f86a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('startwork', sa.Time(), nullable=True))
    op.add_column('restaurants', sa.Column('endwork', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'endwork')
    op.drop_column('restaurants', 'startwork')
    # ### end Alembic commands ###
