"""Change telegram_id to BIGINT

Revision ID: fd867aeed7b7
Revises: d7f02ba4cd1c
Create Date: 2025-03-01 07:23:29.483162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd867aeed7b7'
down_revision: Union[str, None] = 'd7f02ba4cd1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'created_at')
    # ### end Alembic commands ###
