"""Initial migration

Revision ID: fe6881f6444d
Revises: f61180061f15
Create Date: 2025-02-28 13:21:07.929420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6881f6444d'
down_revision: Union[str, None] = 'f61180061f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('retaurant_chat_id', sa.BigInteger(), nullable=True))
    op.alter_column('restaurants', 'admin_telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'admin_telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('restaurants', 'retaurant_chat_id')
    # ### end Alembic commands ###
